title: David Crowley, EAO - ressources partagées
title_full: David Crowley, EAO - ressources partagées entre les sites de cours
description: Portail pour accéder aux cours de David Crowley, EAO et domaine racine hébergeant la configuration partagée entre ces sites (favicônes, styles)

url: "https://physcrowley.github.io"
baseurl: "/"
